### PR TITLE
Fixed readme formatting, fixed and documented METADATA-LOOKUP_TYPE

### PR DESCRIPTION
**Pull request by alalonde**

### CODE REVIEW

**Comment by mcrowson** [comment]
Hey thanks for the PR! I like the Readme fixes, but I'm not sure I follow on the lookuptype change. The reason it is failing is that a test is trying to get that key from the raw XML. Here is the sample XML it is trying to parse and the line it is failing on:

https://github.com/refindlyllc/rets/blob/master/tests/rets_responses/STANDARD-XML/GetMetadata_lookup.xml#L4

Do you have a different xml example that it is not parsing? Is there some other issue this is trying to solve?

**Comment by alalonde** [comment]
Hmm, interesting.  Perhaps we are looking at different versions of the spec?  The XML response I got is here: https://gist.github.com/alalonde/f5e23f848e438140453683cf4a3c2a32

**Comment by mcrowson** [comment]
I was looking at 1.7. https://www.nar.realtor/retsorg.nsf/retsproto1.7d6.pdf

If you check out table 11-19 that is what I'm going off of. It was consistent with the responses we were getting from the rets providers we use. Who is the vendor for the response you gave?

**Comment by alalonde** [comment]
We are using this service: http://rets.nys.mlsmatrix.com/rets/  I'm not sure how to tell which version of the spec they're referring to.

**Comment by mcrowson** [comment]
That is Matrix. A few of the matrix boards we have access to give the same LookupType as you have here and another non-matrix board does as well. So either I've misread the spec or the servers are inconsistent. Likely the former. If you want to update your PR to include a modification of the XML to match the format so the tests pass we can merge this.

**Comment by alalonde** [comment]
Thanks -- I figured nobody was using that particular function anyway since it wasn't documented.  Happy to help.

**Pull request merged**
